export const ADD_COMPETITOR = 'ADD_COMPETITOR';
export const DELETE_COMPETITOR = 'DELETE_COMPETITOR';
export const RESET_COMPETITOR = 'RESET_COMPETITOR ';
export const SHOW_COMPETITOR = 'SHOW_COMPETITOR';
export const HIDE_COMPETITOR = 'HIDE_COMPETITOR';

export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const RECORD_VALUE = 'RECORD_VALUE';
export const SAVE_VALUE = 'SAVE_VALUE';
export const UPDATE_RATING = 'UPDATE_RATING';
export const UPDATE_ALL_RATINGS = 'UPDATE_ALL_RATINGS';

export const SET_TITLE = 'SET_TITLE';
export const SET_DURATION = 'SET_DURATION';
export const SET_MAXVOL = 'SET_MAXVOL';
